Attempt1/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import Attempt1.settings as settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('csearch.urls', namespace='csearch'),
)
]

csearch/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView, FormView
from csearch import views

urlpatterns = [
   url(r'^author/',TemplateView.as_view(template_name='presubmit.html')),
   url(r'^publication/',TemplateView.as_view(template_name='presubmit_pub.html')),
   url(r'^submit_request/', views.search_submit_request, name='submit_request'),
   url(r'^search_author/', views.search, name='searchg'),
   url(r'^search_author_updated/', views.search, name='searchg2'),
   url(r'^search_publication/', views.search_pub, name='searchp'),
   url(r'^list_view/', views.display_list, name='display_list'),
   url(r'^updated/', views.update_list, name='update_list'),
   url(r'^select_papers/', views.select_papers, name='select_papers'),
   url(r'^search_publication_specified/', views.search_pub_specified_paper, name='searchp_specified'),
   url(r'^submitted_filtered/', views.submitted_filtered, name='submitted_filtered')

]

csearch/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

csearch/forms.py
from django import forms
import unidecode

# Form used for searching publications
class PubSearchForm(forms.Form):
   username = forms.CharField(max_length=200)
   choosepaper = forms.BooleanField(initial=False, required=False)

   def clean_user(self):
      username = self.cleaned_data.get('username')
      return username

   def clean_choosepaper(self):
      choosepaper = self.cleaned_data.get('choosepaper')
      return choosepaper

   def clean(self):
      data = self.cleaned_data

      username = data.get('username')
      choosepaper = data.get('choosepaper')
      data['username'] = unidecode.unidecode(username)
      data['choosepaper'] = choosepaper

      return data

# Form used for searching general data
class SearchForm(forms.Form):
   username = forms.CharField(max_length=200)

   def clean_user(self):
      # super(SearchForm, self).clean()
      username = self.cleaned_data.get('username')
      return username

   def clean(self):
      data = self.cleaned_data

      username = data.get('username')
      data['username'] = unidecode.unidecode(username)

      return data

# Form used for searching author with the goal of pulling previously-existing data
class AuthorRepullSearchForm(forms.Form):
   username = forms.CharField(max_length=200)
   includedkey = forms.CharField(max_length=400, required=False)
   excludedkey = forms.CharField(max_length=400, required=False)
   filter = forms.BooleanField(initial=False, required=False)
   repull = forms.BooleanField(initial=False, required=False)

   def clean_user(self):
      # super(SearchForm, self).clean()
      username = self.cleaned_data.get('username')
      return username

   def clean_includedkey(self):
      includedkey = self.cleaned_data.get('includedkey')
      return includedkey

   def clean_excludedkey(self):
      excludedkey = self.cleaned_data.get('excludedkey')
      return excludedkey

   def clean_filter(self):
      filter = self.cleaned_data.get('filter')
      return filter

   def clean_repull(self):
      repull = self.cleaned_data.get('repull')
      return repull

   def clean(self):
      data = self.cleaned_data

      username = data.get('username')
      i_key = data.get('includedkey')
      e_key = data.get('excludedkey')
      data['username'] = username

      filter = data.get('filter')
      if filter == None:
         data['filter'] = False
      else:
         data['filter'] = filter

      repull = data.get('repull')
      if repull == None:
         data['repull'] = False
      else:
         data['repull'] = repull

      data['includedkey'] = i_key
      data['excludedkey'] = e_key

      return data

# Form used for searching author data
class AuthorSearchForm(forms.Form):
   username = forms.CharField(max_length=200)
   includedkey = forms.CharField(max_length=400, required=False)
   excludedkey = forms.CharField(max_length=400, required=False)
   filter = forms.BooleanField(initial=False, required=False)

   def clean_user(self):
      # super(SearchForm, self).clean()
      username = self.cleaned_data.get('username')
      return username

   def clean_includedkey(self):
      includedkey = self.cleaned_data.get('includedkey')
      return includedkey

   def clean_excludedkey(self):
      excludedkey = self.cleaned_data.get('excludedkey')
      return excludedkey

   def clean_filter(self):
      filter = self.cleaned_data.get('filter')
      return filter

   def clean(self):
      data = self.cleaned_data

      username = data.get('username')
      i_key = data.get('includedkey')
      e_key = data.get('excludedkey')
      data['username'] = username

      filter = data.get('filter')
      if filter == None:
         data['filter'] = False
      else:
         data['filter'] = filter

      data['includedkey'] = i_key
      data['excludedkey'] = e_key

      return data

csearch/views.py
from __future__ import unicode_literals

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import expon
import os.path
from scipy.integrate import quad
from scipy.stats import beta
import matplotlib.mlab as mlab

import csearch.api_search.extract_data as extract_data

import unidecode

from django.shortcuts import render, render_to_response
from django.http import HttpResponse
from .forms import SearchForm, AuthorSearchForm, PubSearchForm, AuthorRepullSearchForm

import os
import pandas as pd
from csearch.api_search.analyze_data_individual_data_optimized import find_self_citation_percentage_from_author, find_self_citation_percentage_from_author2,\
    df_clean_exclude, find_self_citation_percentage_from_author2_forward
from csearch.api_search.analyze_data_publication_data_optimized import publication_score, publication_score_bavkwards, publication_score2, publication_score2_f
from csearch.api_search.APP_pull_data_individual import execute_search_pubmed_terminal, execute_search_pubid_terminal, execute_search_pubid_terminal_name, \
    execute_search_pubid_suggest_name, execute_search_pubid_terminal_name_3, execute_search_pubid_terminal_ALERT_TRUE

save_directory = "/Users/mkorovkin/PycharmProjects/Attempt1/csearch/static/"
dataset_directory = "/Users/mkorovkin/Desktop/"

# Deprecated list
xlist = [0.0   , 0.0125, 0.025 , 0.0375, 0.05  , 0.0625, 0.075 , 0.0875,
         0.1   , 0.1125, 0.125 , 0.1375, 0.15  , 0.1625, 0.175 , 0.1875,
         0.2   , 0.2125, 0.225 , 0.2375, 0.25  , 0.2625, 0.275 , 0.2875,
         0.3   , 0.3125, 0.325 , 0.3375, 0.35  , 0.3625, 0.375 , 0.3875,
         0.4   , 0.4125, 0.425 , 0.4375, 0.45  , 0.4625, 0.475 , 0.4875,
         0.5   , 0.5125, 0.525 , 0.5375, 0.55  , 0.5625, 0.575 , 0.5875,
         0.6   , 0.6125, 0.625 , 0.6375, 0.65  , 0.6625, 0.675 , 0.6875,
         0.7   , 0.7125, 0.725 , 0.7375, 0.75  , 0.7625, 0.775 , 0.7875,
         0.8   , 0.8125, 0.825 , 0.8375, 0.85  , 0.8625, 0.875 , 0.8875,
         0.9   , 0.9125, 0.925 , 0.9375, 0.95  , 0.9625, 0.975 , 0.9875]

# Deprecated stats
pct_0 = np.round(0.000000 * 100.0, decimals=2)
pct_25 = np.round(0.030792 * 100.0, decimals=2)
pct_50 = np.round(0.103914 * 100.0, decimals=2)
pct_75 = np.round(0.217391 * 100.0, decimals=2)

# Deprecated test statistics
def get_practical_percentile(x):
    blist = [0.0011655012, 0.0, 0.003649635, 0.0, 0.01858407, 0.0050301813, 0.0, 0.015625, 0.009009009, 0.0021145714, 0.0,
     0.00931677, 0.0032894737, 0.0, 0.0, 0.0, 0.0040650405, 0.002042901, 0.0, 0.011424731, 0.011111111, 0.01884422,
     0.015053763, 0.0114478115, 0.0, 0.005461165, 0.0, 0.0021008404, 0.007950225, 0.004548408, 0.0088417325,
     0.001497006, 0.0, 0.0023391813, 0.032258064, 0.026610645, 0.0013550136, 0.0056497175, 0.0062305294, 0.0,
     0.0008354219, 0.0049806307, 0.0069258264, 0.0020325202, 0.0, 0.0020318849, 0.000621118, 0.0, 0.0045454544, 0.0,
     0.02011963, 0.0056410255, 0.003907946, 0.0040716613, 0.0, 0.054545455, 0.016666668, 0.017897092, 0.015151516,
     0.0073574493, 0.0, 0.01, 0.0086629, 0.0, 0.026845638, 0.010526316, 0.00096153846, 0.0060975607, 0.0, 0.00882353,
     0.004350979, 0.0062240665, 0.0, 0.006302521, 0.0, 0.001010101, 0.003508772, 0.004878049, 0.009186352, 0.0014947683,
     0.007310705, 0.018621974, 0.0023640662, 0.0025839794, 0.0, 0.0031434186, 0.0121951215, 0.019308943, 0.032863848,
     0.0, 0.0023809525, 0.008368201, 0.019157087, 0.00952381, 0.0011299435, 0.007575758, 0.0, 0.009836066, 0.0124223605,
     0.01056338, 0.0, 0.009041592, 0.0010351967, 0.0038043477, 0.0, 0.029850746, 0.0045592706, 0.0042293235,
     0.007867133, 0.0074487897, 0.0, 0.0, 0.0, 0.0, 0.014160156, 0.0952381, 0.0, 0.0, 0.0, 0.00498132]
    blist.sort()
    print(blist)
    count = 0
    for i in blist:
        if x > i:
            count += 1
    return np.float32(count) / np.float32(len(blist)) * 100.0

# Does a string represent an integer?
def represents_int(s):
    try:
        int(s)
        return True
    except ValueError:
        return False

# Format a word based on the quantity (e.g. the "eleventh percentile" versus "second percentile"
def english_ext(x):
    if x % 10 == 1:
        return "st"
    elif x % 10 == 2:
        return "nd"
    elif x % 10 == 3:
        return "rd"
    else:
        return "th"

# Deprecated graphing method using a string instead of a matplotlib graph
def construct_string(ix):
    ar = [0.0, pct_25, pct_50, pct_75, 1.0]
    bk = 0

    for q in range(len(ar) - 1):
        if ix >= ar[q] and ix <= ar[q + 1]:
            bk = q
            break

    x1 = ar[bk]; x2 = ar[bk + 1]
    diff = (x2 - x1)
    diffx2 = ix - x1
    diff_ov = diffx2 / diff * 5
    stop_at = bk * 5 + np.ceil(diff_ov)

    const = "< "
    for i in range(20):
        if i == stop_at:
            const += "* "
        else:
            const += "- "

    return const + ">"

def compute_percentile_pubid(x):
    integ = f_integrate_pubid(x)
    if integ < 0.99:
        return integ
    else:
        return 0.99

# Compute the percentile of an author with self-citations
def f_integrate(x):
    return beta.pdf(x, 1.230, 7.078)

# Compute the percentile of an publication with self-citations
def f_integrate_pubid(x):
    return beta.cdf(x, 0.521, 9.493)

# Compute the percentile of an publication with self-citations
def f_pubid2(x):
    return beta.pdf(x, 0.521, 9.493)

# Show the plot of an publication self-citation distribution
def show_plot_pubid(stat):
    xmax = 1.0
    if stat < 0.15:
        xmax = 0.25
    elif stat < 0.25:
        xmax = stat * 2
    x = np.linspace(0, xmax, 1000)
    plt.plot(xlist, [f_pubid2(x) for x in xlist], 'k')
    plt.title("Distribution of Self-Citation Frequency")
    plt.ylabel("Relative frequency of self-citation rate")
    plt.xlabel("Self-citation rate")
    plt.axvline(x=stat, ymin=0, ymax=1, color='r', linewidth=2)

    img_dir = save_directory + "temp_fig_pub.png"
    print("Saving in directory \"" + img_dir + "\"")
    plt.savefig(img_dir)
    plt.clf()
    plt.close()
    return img_dir

# Compute the percentile of an author with self-citations
def compute_percentile(x):
    return beta.cdf(x, 1.230, 7.078)

# Show the plot of an author self-citation distribution
def show_plot(stat):
    import matplotlib.font_manager as fm
    set([f.name for f in fm.fontManager.ttflist])
    plt.figure()
    xmax = 1.0
    if stat < 0.5:
        xmax = stat * 2.0
        if xmax < 0.25:
            xmax = 0.25
    xlist = np.float32(range(100)) * xmax / 100.0

    # Create the plot in matplotlib
    plt.plot(xlist, [f_integrate(x) for x in xlist], 'k')
    plt.title("Distribution of Self-Citation Frequency")
    plt.ylabel("Min-max scaled relative frequency")
    plt.xlabel("Self-citation rate")
    plt.axvline(x=stat, ymin=0, ymax=1, color='r', linewidth=2)
    img_dir = save_directory + "temp_fig.png"
    print("Saving in directory \"" + img_dir + "\"")
    plt.savefig(img_dir)
    plt.clf()
    plt.close()
    return img_dir

# Format an author name using the PubMed format
def format_author(word):
    to_return = word[(word.index(" ") + 1):] + " " + word[0]
    return to_return.lower()

# Interpret a form request
def search_submit_request(request):
    username = "::ERROR::"
    filter_value = False
    skip = True

    if request.method == "POST":
        # Get the posted form
        my_form = AuthorSearchForm(data=request.POST)

        if my_form.is_valid():
            username = my_form.cleaned_data['username']
            filter_value = my_form.cleaned_data['filter']
            skip = False

    else:
        my_form = AuthorSearchForm()

    if not skip:
        file = open("/Users/mkorovkin/Desktop/temp_file1.txt", "w+")
        file.write("username:" + str(username) + "\nfilter:" + str(filter_value))

    return render(request, 'submit.html', {})

# Deprecated search backup method used for search updates and looping
def search2(request):
    global search_ids

    username = ":"
    filter_value = False
    tfs = "/Users/mkorovkin/Desktop/temp_file1.txt"

    if not os.path.isfile(tfs):
        return render(request, 'failed_to_load.html', {})
    else:
        f_info = open(tfs, "r")
        lines_array = f_info.readlines()
        for line in lines_array:
            if line.startswith("username:"):
                username = line[9:]
            elif line.startswith("filter:"):
                filter_value = line[7:] == "True"

    string_nospace = dataset_directory + "citations_" + username.replace(" ", "_").lower() + str(filter_value) + ".csv"
    if not os.path.isfile(string_nospace):
        execute_search_pubmed_terminal(search_name=username.lower(), filter_value=filter_value)
    if os.path.isfile(string_nospace):
        return HttpResponse("<h1>Title:" + username + "</h1>")
    if os.path.isfile(string_nospace) and not True:
        x, total_found, total_inspected, total_citations = find_self_citation_percentage_from_author2(format_author(username.lower()),
                                                                                                      pd.read_csv(string_nospace))
        percentile_to_return = np.int32(np.ceil(compute_percentile(x) * 100.0))

        practical_percentile = np.ceil(get_practical_percentile(x))

        return render(request, 'submitted.html', {"username": username, "percent": str(np.round(x * 100.0, decimals=2)),
                                                  "twenty_five": pct_25, "fifty": pct_50, "seventy_five": pct_75,
                                                  "graphic": show_plot(x), "percentile": percentile_to_return,
                                                  "total_citations": total_citations,
                                                  "publication_number_ext": "publication" if total_citations == 1 else "publications",
                                                  "percentile_ext": english_ext(percentile_to_return),

csearch/templates/failed_to_load.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>Failed to load {{ type_request }} data for {{ input }}.<br><br></title>
      <h1>Failed to load {{ type_request }} data for {{ input }}.</h1>
      <p>Please check spelling and/or try re-submitting the request.</p>
   </head>
   <body>
   </body>
</html>

csearch/templates/failed_to_load_test.html
<!DOCTYPE html>
<script>
   function CheckboxSubmit(val){
       var counter = 0, // counter for checked checkboxes
       i = 0,       // loop variable
       url = '',    // final url string
       // get a collection of objects with the specified 'input' TAGNAME
       input_obj = document.getElementsByTagName('input');
   // loop through all collected objects
   for (i = 0; i < input_obj.length; i++) {
       // if input object is checkbox and checkbox is checked then ...
       if (input_obj[i].type === 'checkbox' && input_obj[i].checked) {
           // ... increase counter and concatenate checkbox value to the url string
           counter++;
           url = url + input_obj[i].name + '|';
       }
   }
   // display url string or message if there is no checked checkboxes
   if (counter > 0) {
       // remove first "&" from the generated url string
       //url = url.substr(1);
       // display final url string
       //alert(url);
   }
   else {
       alert('There is no checked checkbox');
       url = ''
   }
   document.local_form.username.value = document.local_form.username.value + '|||' + val + '|||' +  url;

     return true;
   }
</script>
<form name="local_form"
   action="{% url 'csearch:update_list' %}"
   method="POST">
{% csrf_token %}
<input type="hidden"
   value={{ input }}
   name="username" />
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>Loaded data for option.</title>
      <h1 style="font-family: 'RobotoDraft', sans-serif;
         font-size: 22px;;
         color: #000;
         margin: 4px 2px;
         border-color: #4285F4;">{{ header }}</h1>
   </head>
   <tbody>
      {% for key, value in links.items %}
      <tr>
         <td>
            <a href="https://www.ncbi.nlm.nih.gov/pubmed/{{ key }}" style="font-family: 'RobotoDraft', sans-serif;
               font-size: 16px;">
               <ul><input type="checkbox"
                  title="{{ value }}"
                  name="checkbox{{ key }}"/>{{ value }}
               </ul>
            </a>
         </td>
      </tr>
      {% endfor %}
   </tbody>
   <button name="submit_button" onclick="CheckboxSubmit({{ operation }})">submit update request</button>
</html>

csearch/templates/intermit_search.html
<!DOCTYPE html>
<html lang="en">
   <head>
      <meta charset="UTF-8">
      <title>Title</title>
      {% for key, value in links.items %}
      <tr>
         <td>
            <a href="https://www.ncbi.nlm.nih.gov/pubmed/{{ key }}" style="font-family: 'RobotoDraft', sans-serif;
               font-size: 16px;">
               <ul><input type="checkbox"
                  title="{{ value }}"
                  name="checkbox{{ key }}"/>Contents{{ value }}
               </ul>
            </a>
         </td>
      </tr>
      {% endfor %}
   </head>
   <body>
   </body>
</html>

csearch/templates/presubmit.html
<html>
   <body bgcolor = "#ecf2fd" style="text-align: left">
      <div>
         <h1 style="
            font-family: 'RobotoDraft', sans-serif;
            font-size: 28px;;
            color: #000;
            margin: 4px 2px;
            margin-bottom: 12px;
            border-color: #4285F4;">
            Citation Search
         </h1>
      </div>
      <div>
         <p style="font-family: 'RobotoDraft', sans-serif;
            font-size: 14px;;
            color: #000;
            margin: 4px 2px;
            border-color: #4285F4;
            margin-bottom: 4%;">
            Search for self-citation rates of publication authors on PubMed. Need more of a descrpition here.
            <br>
            Add some more stuff here.
         </p>
         <form name="form"
            action="{% url 'csearch:searchg' %}"
            method="POST">
            {% csrf_token %}
            <input type="text"
               style="font-family: 'RobotoDraft', sans-serif;
               font-size: 18px;
               width: 20%;
               background-color: #FFFFFF;
               color: #000;
               border-color: #4285F4;
               margin: 4px 2px;
               padding: 2px"
               placeholder="Author name"
               name="username" />
            <br>
            <input type="text"
               style="font-family: 'RobotoDraft', sans-serif;
               font-size: 18px;
               width: 20%;
               background-color: #f1f1f1;
               color: #000;
               border-color: #4285F4;
               margin: 4px 2px;
               padding: 2px"
               placeholder="Keywords to include"
               name="includedkey" />
            <br>
            <input type="text"
               style="font-family: 'RobotoDraft', sans-serif;
               font-size: 18px;
               width: 20%;
               background-color: #f1f1f1;
               color: #000;
               border-color: #4285F4;
               margin: 4px 2px;
               padding: 2px"
               placeholder="Keywords to exclude"
               name="excludedkey" />
            <br>
            <p style="font-family: 'RobotoDraft', sans-serif;
               font-size: 14px;;
               color: #000;
               margin: 4px 2px;
               border-color: #4285F4;
               margin-bottom: 4%;">
               <input type="checkbox"
                  title="Filter to past 7 years"
                  value="unchecked"
                  name="filter"/>
               Filter search to the past 7 years:
               <br>
               <input type="checkbox"
                  title="repull"
                  value="unchecked"
                  name="repull"/>
               Pull new data for author:
            </p>
            <br>
            <br>
            <style>
               .button {
               background-color: #4285F4; /* Green */
               border: none;
               color: white;
               padding: 16px 32px;
               text-align: center;
               text-decoration: none;
               display: inline-block;
               font-size: 18px;
               margin: 4px 2px;
               -webkit-transition-duration: 0.4s; /* Safari */
               transition-duration: 0.4s;
               cursor: pointer;
               }
               .button1 {
               background-color: white;
               color: black;
               border: 2px solid #4285F4;
               }
               .button1:hover {
               background-color: #4285F4;
               color: white;
               }
            </style>
            <button
               style="width: 20%;
               height: 8%;
               font-family: 'RobotoDraft', sans-serif;"
               class="button button1"
               type="submit"
               value="Search">
            Search
            </button>
         </form>
      </div>
   </body>
</html>

csearch/templates/presubmit_pub.html
<html>
   <body bgcolor = "#ecf2fd" style="text-align: left">
      <div>
         <h1 style="
            font-family: 'RobotoDraft', sans-serif;
            font-size: 28px;;
            color: #000;
            margin: 4px 2px;
            margin-bottom: 12px;
            border-color: #4285F4;">
            Citation Search
         </h1>
      </div>
      <div>
         <p style="font-family: 'RobotoDraft', sans-serif;
            font-size: 14px;;
            color: #000;
            margin: 4px 2px;
            border-color: #4285F4;
            margin-bottom: 4%;">
            Search for self-citation rates of publications on PubMed. Need more of a descrpition here.
            <br>
            Add some more stuff here.
            <br>
            <br>
            <i>When searching a publication using title, DO NOT search the full title; search a primary substring instead.</i>
         </p>
         <form name="form"
            action="{% url 'csearch:searchp' %}"
            method="POST">
            {% csrf_token %}
            <input type="text"
               style="font-family: 'RobotoDraft', sans-serif;
               font-size: 18px;
               width: 20%;
               background-color: #FFFFFF;
               color: #000;
               border-color: #4285F4;
               margin: 4px 2px;
               padding: 2px"
               placeholder="PubMed ID..."
               name="username" />
            <input type="checkbox"
               title="Filter to past 7 years"
               value="unchecked"
               name="filter"/>
                match closest result to query
            <br>
            <br>
            <style>
               .button {
               background-color: #4285F4; /* Green */
               border: none;
               color: white;
               padding: 16px 32px;
               text-align: center;
               text-decoration: none;
               display: inline-block;
               font-size: 18px;
               margin: 4px 2px;
               -webkit-transition-duration: 0.4s; /* Safari */
               transition-duration: 0.4s;
               cursor: pointer;
               }
               .button1 {
               background-color: white;
               color: black;
               border: 2px solid #4285F4;
               }
               .button1:hover {
               background-color: #4285F4;
               color: white;
               }
            </style>
            <button
               style="width: 20%;
               height: 8%;
               font-family: 'RobotoDraft', sans-serif;"
               class="button button1"
               type="submit"
               value="Search">
            Search
            </button>
         </form>
      </div>
   </body>
</html>

csearch/templates/select_papers.html
<!DOCTYPE html>
<style>
   .button_cool {
   background-color: #4285F4; /* Green */
   border: none;
   color: white;
   padding: auto auto;
   text-align: left;
   text-decoration: none;
   display: inline-block;
   font-size: 16px;
   margin: 4px 2px;
   -webkit-transition-duration: 0.4s; /* Safari */
   transition-duration: 0.4s;
   cursor: pointer;
   }
   .button1 {
   background-color: white;
   color: black;
   border: 2px solid #4285F4;
   }
   .button1:hover {
   background-color: #4285F4;
   color: white;
   }
</style>
<script>
   function CheckboxSubmit(val){
   document.local_form.username.value = document.local_form.username.value + '|||' + val;
   // FOR DEBUGGING: alert(document.local_form.username.value + '|||' + val);
     return true;
   }
</script>
<form name="local_form"
   action="{% url 'csearch:searchp_specified' %}"
   method="POST">
{% csrf_token %}
<input type="hidden"
   value={{ input }}
   name="username" />
<html lang="en">
    <body bgcolor="#ecf2fd">
       <head>
          <meta charset="UTF-8">
          <title>Loaded data for option.</title>
          <h1 style="font-family: 'RobotoDraft', sans-serif;
             font-size: 22px;;
             color: #000;
             margin: 4px 2px;
             border-color: #4285F4;">{{ header }}</h1>
       </head>
       <tbody>
          {% for key, value in papers.items %}
          <tr>
             <td style="font-family: 'RobotoDraft', sans-serif;
                font-size: 16px;">
                <ul><button class="button_cool button1" style="width: 40%"
                   title="{{ key }}"
                   name="button{{ key }}"
                   onclick="CheckboxSubmit({{ key }}); document.local_form.submit()">{{ value }}</button>
                </ul>
             </td>
          </tr>
          {% endfor %}
       </tbody>
    </body>
</html>

csearch/templates/submit.html
<head>
   <script src="http://code.jquery.com/jquery-latest.min.js"></script>
</head>
<body>
   [
   <div id="output_box"></div>
   ]
   <script>
      $(document).ready(function() {
        $.ajaxSetup({ cache: false }); // This part addresses an IE bug.  without it, IE will only load the first number and will never refresh
        let my_refresh = setInterval(function() {
          $('#output_box').load('/search_author/');
        }, 1000);
      });

   </script>
</body>

csearch/templates/submit2.html
<head>
   <script src="http://code.jquery.com/jquery-latest.min.js"></script>
</head>
<body>
   [
   <div id="output_box"></div>
   ]
   <script type="text/javascript">
      let frm = $('/search_author/');
      frm.submit(function () {
          $.ajax({
              type: frm.attr('POST'),
              url: frm.attr('action'),
              data: frm.serialize(),
              success: function (data) {
                  $('#output_box').load('/search_author/');
              },
              error: function(data) {
                  $("#output_box").html("Something went wrong!");
              }
          });
          return false;
      });
   </script>
</body>

csearch/templates/submitted_author_depricated.html
<html>
   <body bgcolor="#ecf2fd">
      <h1 style="font-family: 'RobotoDraft', sans-serif;
         font-size: 28px;;
         color: #000;
         margin: 4px 2px;
         border-color: #4285F4;
         margin-bottom: 2%;">
         Self-citation frequency: <mark>{{ percent }}%</mark>{{ xx }}
      </h1>
      <p>
         The PubMed website was searched for the publications of author "<strong>{{ username }}</strong>";
         <br>
         A sample size of {{ total_citations }} {{ publication_number_ext }} was used to estimate the above statistic.
         <br>
         There were found to be {{ ss_number }} occurrences of self-citation; {{ ss_insp }} total references were inspected.
         <br><br>
         Author "{{ username }}" is in <strong>{{ percentile }}{{ percentile_ext }} percentile</strong> (mathematical) of large-sample self-citation frequency.
         This author is in the <strong>{{ percentile_practical }}{{ percentile_practical_ext }} percentile</strong> (practical).
         <br><br>
         <strong>Statistics for scaling:</strong>
         <br>
         25th percentile: {{ twenty_five }}%
         <br>
         50th percentile: {{ fifty }}%
         <br>
         75th percentile: {{ seventy_five }}%
         <br>
         <br>
         <i>Note: these statistics are computed only from the "backwards-in-time" self-citation rates.</i>
         <br>
      </p>
      {% load static %}
      <img src="{% static "temp_fig.png" %}" border="2px" style="margin: 4px 2px; border-color: #4285F4;"/>
   </body>
</html>